uploads = []

[[generated]]
id = "Rh33-DwO9tScFozoJG-fZ"
uri = "file://attached_assets/hero.png"
type = "image"
title = "Hero event security"

[[generated]]
id = "4Y4UfdxknTIKPRbZWvdxJ"
uri = "file://attached_assets/generated_images/stewarding_purple.png"
type = "image"
title = "stewarding purple hi-vis"

[[generated]]
id = "Z0vZeBqW14Ha9mubqV3dv"
uri = "file://attached_assets/generated_images/fire_safety_red.png"
type = "image"
title = "fire safety red hi-vis"

[[generated]]
id = "4dWJv_hDU4NXYxhEvtO70"
uri = "file://attached_assets/generated_images/stewarding_card.png"
type = "image"
title = "stewards classic car show"

[[generated]]
id = "2mqj-NftaNwHcTNGTx_lg"
uri = "file://attached_assets/generated_images/fire_safety_card.png"
type = "image"
title = "fire safety red hi vis"

[[generated]]
id = "WecLjkXYZzMeYlG5AC-JC"
uri = "file://attached_assets/generated_images/stewarding_base.png"
type = "image"
title = "stewards candid classic car show"

[[generated]]
id = "FtTZmDjj_tlmeKp_UM0A9"
uri = "file://attached_assets/generated_images/fire_safety_base.png"
type = "image"
title = "fire candid red vests"

[[outputs]]
id = "C2jbvju873a8c6mw3ryHh"
uri = "file://attached_assets/generated_images/stewarding_card.png"
type = "image"
title = "Stewarding card — cropped"

[[outputs]]
id = "zCQOsMNng_v94dTdY3Dsj"
uri = "file://attached_assets/generated_images/fire_safety_card.png"
type = "image"
title = "Fire Safety card — cropped"
